Feature/create dynamic form templates
cpandya231/DynamicFormDesigns-FrontEnd pull request #19
Opened 2022-05-25 13:39 UTC by akashP2312

2022-05-26 06:21 UTC, cpandya231 requested changes
Lets keep submit and cancel button in one line. 
![image](https://user-images.githubusercontent.com/38644871/170429191-30e6a180-4c9b-4659-a9d9-165c1ecd9da0.png)

2022-05-26 06:27 UTC, cpandya231 requested changes

2022-05-26 06:27 UTC, cpandya231 commented on src/app/forms/form-workflow/add-edit-workflow-state/add-edit-workflow-state.component.html
> +                    <button class="btn save_button" type="submit"> Save State</button>
Lets use same call to action button style everywhere. We should use $main-teal for buttons and $main-teal-dark on hover.

2022-05-26 06:28 UTC, cpandya231 commented
Also, I can not add sub-state under existing state. It gives error. Looks like d3-org-chart is not getting proper data.

2022-06-10 13:19 UTC, akashP2312 commented
Please check now

2022-06-14 14:18 UTC, cpandya231 commented
Some more points

-  We should redirect to Form Workflow tab when form template is created
-  We should put validation on Previous state dropdown, I am able to create state without any previous state and that breaks the UI. 
- To solve above, I think we should by default create one parent state with default name.
- When we add child states, save workflow button disappears.

2022-06-15 17:41 UTC, akashP2312 commented
Done changes

2022-06-16 04:56 UTC, cpandya231 approved these changes

2022-06-17 04:13 UTC, merged